### ISSUE TITLE
Forgot password functionality

### ISSUE THREAD

**Issue by AnubhavKrRajat** [AnubhavKrRajat/COMP-8967_Assignment#11]

**Comment by abdullah9932** [comment]
Completed the forgot password api

**Comment by abdullah9932** [comment]
First Step:
Send POST request to:
http://internship-project-auth.herokuapp.com/ForgotPassword
with body:
{
"email" : "email"
}

Response:
It will first check if a user with that email exists or not.
if user will exists it will return reset code sent successfully and will send email to the user and add that code in document(database).

if email doesn't exist it will return no user found.

Second Step:
Ask the user to write that reset code in a field and new password with it.
send that code and new password to this API:
http://internship-project-auth.herokuapp.com/ResetPassword
method: POST
body: 
{
"resetToken" : "token",
"password" : "password"
}

Response:
In Response, if token is correct then it will update the password and return the password updated successfully.
If the token is not correct it will return an Incorrect token.
