### ISSUE TITLE
Creating UI page for login

### ISSUE THREAD

**Issue by AnubhavKrRajat** [AnubhavKrRajat/COMP-8967_Assignment#2]

**Comment by sharmaSagar01** [comment]
# Created Login form for the Application 
* Added Input field for Email
* Added Input field for Password
* Added Login Button
* Added a Login Button for Google Sign In

![image](https://user-images.githubusercontent.com/37947735/192355740-42511448-a957-4b11-8a66-6acae4cf544e.png)
