### ISSUE TITLE
Creating UI page for sign up

### ISSUE THREAD

**Issue by AnubhavKrRajat** [AnubhavKrRajat/COMP-8967_Assignment#3]

**Comment by sharmaSagar01** [comment]
# Created UI for Sign Up

- Added Input field for Full Name
- Added Input field for Email
- Added Input field for Password
- Added Input field for Confirm Password
- Added Links to the Sign In Page

![image](https://user-images.githubusercontent.com/37947735/192356433-de6c06cc-e8f9-4d4e-a671-a806dd6ca12c.png)
