### ISSUE TITLE
Implement login functionality

### ISSUE THREAD

**Issue by AnubhavKrRajat** [AnubhavKrRajat/COMP-8967_Assignment#7]

**Comment by abdullah9932** [comment]
Completed the implementation of login user through email and password

**Comment by abdullah9932** [comment]
end point to test login api:
http://internship-project-auth.herokuapp.com/LoginUser
method: Post
body:
{
"email" : "email",
"password" : "password"
}

Response:
In response if email and password is correct it will return that user data.

If incorrect it will return incorrect username and password.
