### ISSUE TITLE
Implementing user registeration functionality

### ISSUE THREAD

**Issue by AnubhavKrRajat** [AnubhavKrRajat/COMP-8967_Assignment#9]

**Comment by abdullah9932** [comment]
Successfully implemented the registration of the user end point of API.

**Comment by abdullah9932** [comment]
http://internship-project-auth.herokuapp.com/RegisterUser
method:POST
request body:
{
"email" : "email",
"password" : "password",
"bio" : "bio",
"photo": "photo link",
"phone" : "phone",
"name" : "name"
}

Response:
In Response if successful it will return user registered successfully.
